version: 2.1

orbs:
  path-filtering: circleci/path-filtering@0.1.3

# This allows you to use CircleCI's dynamic configuration feature
setup: true

# The main purpose of this setup config is to identify which folders contain code changes,
# letting us choose which model to retrain and redeploy
workflows:
  run-filter:
    jobs:
      - path-filtering/filter:
          # Compare files on main
          base-revision: main
          # 3-column space-separated table for mapping: `path-to-test parameter-toset value-for-parameter` for each row
          mapping: |
            abalone_model/.* deploy-abalone true
            churn_model/.* deploy-churn true
          config-path: ".circleci/dynamic_config.yml"
 
